### ISSUE TITLE
Ver.4.3.0においてFPS上限が変更できない

### ISSUE THREAD

**Issue by Toki0916** [rexent-gx/PowerPaimon#1]
2023/12/20に原神Ver.4.3.0が公式よりリリースされましたが、アップデート完了後よりPowerPaimon v2.0.1.1においてFPS上限の解除ができなくなる問題が発生しています。

![スクリーンショット 2023-12-20 122955](https://github.com/rexent-gx/PowerPaimon/assets/104895162/742031f5-39eb-4741-8bbd-fc40c148a616)
こちらがPowerPaimonより原神を起動した際に現れるエラーです。
このポップアップが出た状態でもその後自動的に原神は起動しますがポップアップが消えることは無く、FPSも変更できていない状態でゲームが始まります。
またこのポップアップはGenshinImpact.exeが終了するまでは✕ボタンやOKを押しても直後に再度表示される状態となっています。

PowerPaimonを経由せずに公式ランチャーから起動した場合は問題ないので、バージョンアップに起因する問題かと思われます。
対応のほどよろしくお願いします。

Windowsの仕様
Windows 11 Home 22H2
OS build 22621.2283
64bit operating system x64

原神バージョン
OSRELWin4.3.0_R19920066_S19850069_D19912525

PowerPaimonの設定
PowerPaimon v2.0.1.1
言語 : システムのデフォルト（日本語）
FPS : 240
起動時に最小化 : false
プログラムを自動で終了する : true
省電力機能の有効化 : false
プロセスの優先度 : Realtime
VSyncを自動で無効化 : false
ポップアップウィンドウモード : true
フルスクリーン : false
カスタム解像度 : false
ウィンドウモード : Borderless
モニター番号 : 2
DLL : なし

**Comment by catteol** [comment]
バージョン4.3への対応を行ったv2.1.0をリリースしました。
お手数ですが、[こちら](https://github.com/rexent-gx/PowerPaimon/releases/latest)から最新版.exeをダウンロードの上、旧PowerPaimonを上書き更新していただけると幸いです。
