### ISSUE TITLE
Genshin Impact Patch 4.7 broke functionality of current release version of PowerPaimon (( 3.0.3 ))

### ISSUE THREAD

**Issue by MylesWow** [rexent-gx/PowerPaimon#2]
PowerPaimon broken as of current patch.
![image](https://github.com/catteol/PowerPaimon/assets/15186514/d157c6ba-c950-4133-9c01-e73872a31c0e)
^^^

 please update soon-~

I love your tool! I can't play the game anymore without it. 240 FPS is so smooth.

**Comment by catteol** [comment]
Thank you for your report!

I think you're using the latest version but please download the latest .exe again, overwrite it and retry to launch, because it seems to work properly under my condition.

**Comment by MylesWow** [comment]
Okay, yeah. Replaced the exe and there was a new version update of .NET 8.0.6 that popped up when it first ran. Updated+everything works fine again, thanks!

![image](https://github.com/catteol/PowerPaimon/assets/15186514/fcaa6e40-27fb-42d2-a7e7-27429c83b225)
